package database

import "log"

func RunMigrations() error {
	for i, m := range migrationSQL {
		if _, err := DB.Exec(m); err != nil {
			log.Printf("Migration %d failed: %v", i, err)
			return err
		}
	}
	log.Println("Database migrations completed")
	return nil
}

var migrationSQL = []string{
	`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`,
	`CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), github_id BIGINT UNIQUE, username VARCHAR(255), email VARCHAR(255) UNIQUE, password_hash VARCHAR(255), avatar_url TEXT, role VARCHAR(50) DEFAULT 'member', created_at TIMESTAMPTZ DEFAULT NOW())`,
	`ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255)`,
	`CREATE TABLE IF NOT EXISTS api_keys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, name VARCHAR(255), key_hash VARCHAR(255), scopes TEXT[], expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS workspaces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255), owner_id UUID REFERENCES users(id) ON DELETE CASCADE, deploy_policy VARCHAR(50) DEFAULT 'cancel', created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS workspace_members (workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE CASCADE, role VARCHAR(50), PRIMARY KEY (workspace_id, user_id))`,
	`CREATE TABLE IF NOT EXISTS project_folders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW())`,
	`ALTER TABLE projects ADD COLUMN IF NOT EXISTS folder_id UUID`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='projects_folder_id_fkey') THEN ALTER TABLE projects ADD CONSTRAINT projects_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES project_folders(id) ON DELETE SET NULL; END IF; END $$`,
	`CREATE INDEX IF NOT EXISTS idx_project_folders_workspace_id ON project_folders(workspace_id)`,
	`CREATE INDEX IF NOT EXISTS idx_projects_folder_id ON projects(folder_id)`,
	`CREATE TABLE IF NOT EXISTS environments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID REFERENCES projects(id) ON DELETE CASCADE, name VARCHAR(255), is_protected BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS services (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, project_id UUID, environment_id UUID, name VARCHAR(255), type VARCHAR(50), runtime VARCHAR(50), repo_url TEXT, branch VARCHAR(255) DEFAULT 'main', build_command TEXT, start_command TEXT, dockerfile_path VARCHAR(255), docker_context VARCHAR(255), image_url TEXT, health_check_path VARCHAR(255), port INT DEFAULT 10000, auto_deploy BOOLEAN DEFAULT TRUE, is_suspended BOOLEAN DEFAULT FALSE, max_shutdown_delay INT DEFAULT 30, pre_deploy_command TEXT, static_publish_path VARCHAR(255), schedule VARCHAR(255), plan VARCHAR(50) DEFAULT 'starter', instances INT DEFAULT 1, status VARCHAR(50) DEFAULT 'created', container_id VARCHAR(255), host_port INT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS env_vars (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_type VARCHAR(50), owner_id UUID, key VARCHAR(255), encrypted_value TEXT, is_secret BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS env_groups (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS env_group_memberships (service_id UUID REFERENCES services(id) ON DELETE CASCADE, env_group_id UUID REFERENCES env_groups(id) ON DELETE CASCADE, PRIMARY KEY (service_id, env_group_id))`,
	`CREATE TABLE IF NOT EXISTS disks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_id UUID REFERENCES services(id) ON DELETE CASCADE, name VARCHAR(255), mount_path VARCHAR(255), size_gb INT, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS custom_domains (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_id UUID REFERENCES services(id) ON DELETE CASCADE, domain VARCHAR(255), verified BOOLEAN DEFAULT FALSE, tls_provisioned BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS deploys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_id UUID REFERENCES services(id) ON DELETE CASCADE, trigger VARCHAR(50), status VARCHAR(50) DEFAULT 'pending', commit_sha VARCHAR(255), commit_message TEXT, branch VARCHAR(255), image_tag VARCHAR(255), build_log TEXT, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ, created_by UUID)`,
	`CREATE TABLE IF NOT EXISTS managed_databases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), plan VARCHAR(50), pg_version INT DEFAULT 16, container_id VARCHAR(255), host VARCHAR(255), port INT DEFAULT 5432, db_name VARCHAR(255), username VARCHAR(255), encrypted_password TEXT, status VARCHAR(50) DEFAULT 'creating', created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS managed_keyvalue (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), plan VARCHAR(50), container_id VARCHAR(255), host VARCHAR(255), port INT DEFAULT 6379, encrypted_password TEXT, maxmemory_policy VARCHAR(50) DEFAULT 'allkeys-lru', status VARCHAR(50) DEFAULT 'creating', created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS blueprints (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255), repo_url TEXT, branch VARCHAR(255), file_path VARCHAR(255) DEFAULT 'render.yaml', last_synced_at TIMESTAMPTZ, last_sync_status VARCHAR(50), created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS blueprint_resources (blueprint_id UUID REFERENCES blueprints(id) ON DELETE CASCADE, resource_type VARCHAR(50), resource_id UUID, resource_name VARCHAR(255))`,
	`CREATE TABLE IF NOT EXISTS backups (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_type VARCHAR(50), resource_id UUID, file_path TEXT, size_bytes BIGINT, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ, status VARCHAR(50))`,
	`CREATE TABLE IF NOT EXISTS audit_log (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID, user_id UUID, action VARCHAR(255), resource_type VARCHAR(50), resource_id UUID, details_json JSONB, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS billing_customers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, stripe_customer_id VARCHAR(255) UNIQUE NOT NULL, stripe_subscription_id VARCHAR(255), payment_method_last4 VARCHAR(4), payment_method_brand VARCHAR(50), subscription_status VARCHAR(50) DEFAULT 'incomplete', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS billing_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), billing_customer_id UUID NOT NULL REFERENCES billing_customers(id) ON DELETE CASCADE, stripe_subscription_item_id VARCHAR(255) UNIQUE NOT NULL, stripe_price_id VARCHAR(255) NOT NULL, resource_type VARCHAR(50) NOT NULL, resource_id UUID NOT NULL, resource_name VARCHAR(255), plan VARCHAR(50) NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`ALTER TABLE users ADD COLUMN IF NOT EXISTS github_access_token TEXT`,
	`CREATE TABLE IF NOT EXISTS registered_domains (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, workspace_id UUID REFERENCES workspaces(id) ON DELETE SET NULL, domain_name VARCHAR(255) UNIQUE NOT NULL, tld VARCHAR(63) NOT NULL, provider VARCHAR(50) DEFAULT 'mock', provider_domain_id VARCHAR(255), status VARCHAR(50) DEFAULT 'pending', expires_at TIMESTAMPTZ, auto_renew BOOLEAN DEFAULT TRUE, whois_privacy BOOLEAN DEFAULT TRUE, locked BOOLEAN DEFAULT FALSE, cost_cents INT DEFAULT 0, sell_cents INT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS dns_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), domain_id UUID NOT NULL REFERENCES registered_domains(id) ON DELETE CASCADE, record_type VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, value TEXT NOT NULL, ttl INT DEFAULT 3600, priority INT DEFAULT 0, managed BOOLEAN DEFAULT FALSE, provider_record_id VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS domain_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), domain_id UUID NOT NULL REFERENCES registered_domains(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR(50) NOT NULL, amount_cents INT DEFAULT 0, status VARCHAR(50) DEFAULT 'completed', details JSONB, created_at TIMESTAMPTZ DEFAULT NOW())`,
	`ALTER TABLE blueprints ALTER COLUMN last_sync_status TYPE TEXT`,
	`CREATE TABLE IF NOT EXISTS preview_environments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, service_id UUID REFERENCES services(id) ON DELETE SET NULL, repository VARCHAR(512) NOT NULL, pr_number INT NOT NULL, pr_title TEXT, pr_branch VARCHAR(255), base_branch VARCHAR(255), commit_sha VARCHAR(255), status VARCHAR(50) DEFAULT 'provisioning', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), closed_at TIMESTAMPTZ)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_preview_env_workspace_repo_pr ON preview_environments(workspace_id, repository, pr_number)`,
	`CREATE TABLE IF NOT EXISTS one_off_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, service_id UUID REFERENCES services(id) ON DELETE SET NULL, name VARCHAR(255) NOT NULL, command TEXT NOT NULL, status VARCHAR(50) DEFAULT 'pending', exit_code INT, logs TEXT DEFAULT '', created_by UUID REFERENCES users(id) ON DELETE SET NULL, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE INDEX IF NOT EXISTS idx_one_off_jobs_service_created ON one_off_jobs(service_id, created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS service_autoscaling_policies (service_id UUID PRIMARY KEY REFERENCES services(id) ON DELETE CASCADE, enabled BOOLEAN DEFAULT FALSE, min_instances INT DEFAULT 1, max_instances INT DEFAULT 1, cpu_target_percent INT DEFAULT 70, memory_target_percent INT DEFAULT 75, scale_out_cooldown_sec INT DEFAULT 120, scale_in_cooldown_sec INT DEFAULT 180, last_scaled_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE TABLE IF NOT EXISTS service_instances (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE, container_id VARCHAR(255) NOT NULL, host_port INT NOT NULL, role VARCHAR(32) DEFAULT 'replica', status VARCHAR(50) DEFAULT 'live', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE INDEX IF NOT EXISTS idx_service_instances_service_id ON service_instances(service_id)`,
	`CREATE TABLE IF NOT EXISTS managed_database_replicas (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), primary_database_id UUID NOT NULL REFERENCES managed_databases(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, region VARCHAR(128) DEFAULT 'same-node', container_id VARCHAR(255), host VARCHAR(255), port INT, status VARCHAR(50) DEFAULT 'creating', replication_mode VARCHAR(32) DEFAULT 'async', lag_seconds INT DEFAULT 0, promoted BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
	`CREATE INDEX IF NOT EXISTS idx_db_replicas_primary ON managed_database_replicas(primary_database_id)`,
	`ALTER TABLE managed_databases ADD COLUMN IF NOT EXISTS ha_enabled BOOLEAN DEFAULT FALSE`,
	`ALTER TABLE managed_databases ADD COLUMN IF NOT EXISTS ha_strategy VARCHAR(32) DEFAULT 'none'`,
	`ALTER TABLE managed_databases ADD COLUMN IF NOT EXISTS standby_replica_id UUID`,
	`ALTER TABLE services ADD COLUMN IF NOT EXISTS project_id UUID`,
	`ALTER TABLE services ADD COLUMN IF NOT EXISTS environment_id UUID`,
	`CREATE TABLE IF NOT EXISTS saml_sso_configs (workspace_id UUID PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE, enabled BOOLEAN DEFAULT FALSE, entity_id VARCHAR(512) NOT NULL, acs_url VARCHAR(1024) NOT NULL, metadata_url VARCHAR(1024), idp_sso_url VARCHAR(1024), idp_cert_pem TEXT, allowed_domains TEXT[] DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`,
}
