apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: railpush-control-plane-console
  namespace: railpush
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - railpush.com
        - www.railpush.com
      secretName: railpush-console-tls
  rules:
    - host: railpush.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: railpush-control-plane
                port:
                  name: http
    - host: www.railpush.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: railpush-control-plane
                port:
                  name: http
