apiVersion: v1
kind: ResourceQuota
metadata:
  name: railpush-quota
  namespace: railpush
spec:
  hard:
    pods: "1000"
    services: "1000"
    services.loadbalancers: "0"
    services.nodeports: "50"
    persistentvolumeclaims: "1000"
    configmaps: "5000"
    secrets: "5000"
    count/ingresses.networking.k8s.io: "1000"
    count/jobs.batch: "2000"
    count/cronjobs.batch: "1000"
    requests.cpu: "200"
    requests.memory: 500Gi
    limits.cpu: "400"
    limits.memory: 1Ti
    requests.storage: 20Ti
